### ISSUE TITLE
Question about CentOS 7.9

### ISSUE THREAD

**Issue by kazimierzbudzyk** [openlogic/AzureBuildCentOS#101]
Hello!

CentOS 7.9 got released fairly recently, I'm curious when is it planned to land here?

Best,
Kaz

**Comment by N3WWN** [comment]
Hi Kaz!

I am attempting to get the CentOS 7.9 images released within the next week or so.

Thanks for inquiring!

**Comment by N3WWN** [comment]
@kazimierzbudzyk Sorry for not following up sooner, but the CentOS 7.9 image was published on Nov 23, 2020.

**Comment by tbugfinder** [comment]
Who could build those CentOS-HPC 7.9 images?

**Comment by N3WWN** [comment]
Hi @tbugfinder !

I will be able to build a CentOS-HPC 7.9 image once the azhpc-images project provides support for CentOS 7.9.

See also: https://github.com/Azure/azhpc-images/issues/50#issuecomment-781364175

Thanks!
