### ISSUE TITLE
CentOS 8 Repo not pointing to newest release

### ISSUE THREAD

**Issue by Klaas-** [openlogic/AzureBuildCentOS#113]
Hi,
I think you forgot to change http://olcentgbl.trafficmanager.net/centos/8/ to point to http://olcentgbl.trafficmanager.net/centos/8.4.2105/
8 is still pointing towards the 8.3 release which does not receive updates anymore.

Greetings
Klaas

**Comment by N3WWN** [comment]
Thanks for pointing this out!

The master repos have been updated and the client repos will receive the updated link when they next sync.

**Comment by Klaas-** [comment]
okay, I'll recheck it tomorrow and provide feedback

**Comment by Klaas-** [comment]
@N3WWN working as expected now, thank you for the quick resolve!

**Comment by Klaas-** [comment]
Follow Up on the 8.4 update. If you use Azure Update Management you may see a lot of failed updates:
`ERROR:  |- Package failed to install: dbxtool.x86_64 (8-5.el8_3.2).   |- Error code: 1. Command used: sudo env ACCEPT_EULA=Y yum -y install dbxtool-8-5.el8_3.2.x86_64  |- Command output: Last metadata expiration check: 1 day, 1:02:03 ago on Tue 29 Jun 2021 08:44:22 AM UTC. Error:   Problem: problem with installed package fwupd-1.5.5-3.el8.x86_64   - installed package fwupd-1.5.5-3.el8.x86_64 obsoletes dbxtool < 9 provided by dbxtool-8-5.el8_3.2.x86_64   - package fwupd-1.5.5-3.el8.x86_64 obsoletes dbxtool < 9 provided by dbxtool-8-5.el8_3.2.x86_64   - conflicting requests (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)`
From what I can tell this is because update management is trying to update packages individually instead of running a complete transaction (ie dnf update -y). I suggested they change their behaviour because of speed effects in https://feedback.azure.com/forums/905242-update-management/suggestions/40348771-speed-up-enterprise-linux-rhel-centos-updates but this was never looked at :) Maybe you can use this issue to get them to reconsider their idea of updating :)

**Comment by N3WWN** [comment]
@Klaas- Thanks!  I've reached out to my contacts within Microsoft to see if they have any insight.

**Comment by Klaas-** [comment]
Hi @N3WWN 

http://olcentgbl.trafficmanager.net/centos/8/ points to 8.4 not 8.5 :) Could you please update that?

**Comment by N3WWN** [comment]
Hi @Klaas-

You beat me to it.  I had this on my TODO list for today. :) 

The master repos are updating right now and the client repos will receive the updated link when they next sync.

**Comment by Klaas-** [comment]
thanks :)
