### ISSUE TITLE
WALinuxAgent 2.3.1.1 spams `NameError: name 'get_python_cmd' is not defined` errors

### ISSUE THREAD

**Issue by servizig** [openlogic/AzureBuildCentOS#116]
After upgrading WALinuxAgent package to the 2.3.1.1 version there are loads of messages like this:
```
2021-08-21T12:18:54.354328Z INFO Daemon Daemon Installed Agent WALinuxAgent-2.3.1.1 is the most current agent
2021-08-21T12:18:54.354483Z WARNING Daemon Daemon Agent WALinuxAgent-2.3.1.1 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with exception: name 'get_python_cmd' is not defined
2021-08-21T12:18:54.354588Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.3.1.1 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with exception: name 'get_python_cmd' is not defined Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/azurelinuxagent/ga/update.py", line 156, in run_latest
    cmds[0] = get_python_cmd()
NameError: name 'get_python_cmd' is not defined
, duration=0
```
I've manually downloaded rpm from [here](http://olcentgbl.trafficmanager.net/openlogic/8/openlogic/x86_64/RPMS/WALinuxAgent-2.3.1.1-1_ol001.el8.noarch.rpm) and indeed there is get_python_cmd function call on line 156, however, this function is not defined anywhere. In the original WALinuxAgent repo this line look like [this](https://github.com/Azure/WALinuxAgent/blob/v2.3.1.1/azurelinuxagent/ga/update.py#L156). What's strange is that function is present in [this](https://github.com/Azure/WALinuxAgent/blob/74e58ee32fd844738cc4ed9339b5e3b92b38d525/azurelinuxagent/ga/update.py#L94) commit.

I'm not sure what happened. Any ideas?

**Comment by Klaas-** [comment]
I think openlogic breaks the package in build, check the srpm http://olcentgbl.trafficmanager.net/openlogic/8/openlogic/x86_64/SRPMS/WALinuxAgent-2.3.1.1-1_ol001.el8.src.rpm - it's being broken in 0001-Add-inital-redhat-build-support.patch

they re-add the get_python_cmd usage but don't readd the function
https://github.com/Azure/WALinuxAgent/commit/5ea00ef00d31ead502f663fbcf62c3cb798aa507

as a quick fix, I think you can just partly reverse the patch from srpm:
```
--- a/azurelinuxagent/ga/update.py.orig
+++ b/azurelinuxagent/ga/update.py
@@ -153,9 +153,8 @@ class UpdateHandler(object):
 
             # Launch the correct Python version for python-based agents
             cmds = textutil.safe_shlex_split(agent_cmd)
-            if cmds[0].lower() == "python":
-                cmds[0] = sys.executable
-                agent_cmd = " ".join(cmds)
+            cmds[0] = get_python_cmd()
+            agent_cmd = " ".join(cmds)
 
             self._evaluate_agent_health(latest_agent)
 
```

**Comment by Klaas-** [comment]
@N3WWN I think this is something for you, also the spec is missing from https://github.com/openlogic/AzureBuildCentOS/tree/master/rpm/spec -- do you acually need to build the waagent packages yourself? I mean centos/rhel has it packaged already and if it works for rhel, it should work for your centos as well :)

**Comment by N3WWN** [comment]
@Klaas- We were asked to build WALinuxAgent 2.3.1.1 by Microsoft since they are unable to get Red Hat to rebase the WALinuxAgent included with EL7 and EL8 to 2.3.1.1.  

@hjarvard - I am examining the patches now and will post an update soon.

**Comment by Klaas-** [comment]
you are packaging WALinuxAgent 2.3.1.1 to be included in RHEL and CentOS on Azure? Or just CentOS?

I do not see a bz to rebase walinuxagent, if you want Red Hat do build it you need to open a bz like https://bugzilla.redhat.com/show_bug.cgi?id=1972102 for EL8.
RHEL7 is already in Maintenance Support 2 so you'll need a really good reason for a new walinuxagent version :)

But what I orignally meant was more "current version of walinuxagent in rhel 8 works, why do you need a newer one for CentOS8 ?" :)

**Comment by N3WWN** [comment]
@Klaas- I suppose anyone that uses the OpenLogic repo could utilize WALinuxAgent 2.3.1.1 ;)  

I'm not involved in the RHEL image builds, so not sure what approach they will take.

The reason for a newer WALinuxAgent RPM was to address an IPoIB issue: https://github.com/Azure/azhpc-images/pull/90

**Comment by N3WWN** [comment]
@hjarvard @Klaas- I just published WALinuxAgent-2.3.1.1-1_ol002.el8 which resolves the issue by removing the patch chunk that references get_python_cmd().

Please let me know if you encounter any further issues with WALinuxAgent 2.3.1.1

Thanks!

**Comment by Klaas-** [comment]
> The reason for a newer WALinuxAgent RPM was to address an IPoIB issue: Azure/azhpc-images#90

you can get Red Hat to backport fixes for specific issues if the priority is high enough -- Microsoft should have a Red Hat integration Team -- get them to prioritize it with Red Hat

**Comment by servizig** [comment]
@N3WWN I've just updated WALinuxAgent on a couple servers and everything works fine. Thank you!
@Klaas- And a personal thank you for the swift reply which cleared my confusion!
