### ISSUE TITLE
Centos cloud instance SIG issue

### ISSUE THREAD

**Issue by lkd-10gen** [openlogic/AzureBuildCentOS#15]
Howdy, sorry about this weird bug report but there's no other way  to get the build team's attention that I can find.

So this RPMspec looks fine.  Whomever's packaging the Azure image forgot to ensure that there's a preset so that `%systemd_post` enables the `waagent.service` unit, not just copies it into position.  Please advise if I should redirect this elsewhere, like centos-devel@

**Comment by szarkos** [comment]
Hi @lkd-10gen,

The files here are primarily used to build the CentOS images we have in the Azure Marketplace, which are built by Roguewave Software (formerly Openlogic).  So they are a bit different than the kickstart files that create the official images on cloud.centos.org.  Although at some point all these things will probably merge closer together.

I presume this is related to this bug: https://bugs.centos.org/view.php?id=13264 ?  According to KB's email on the centos-devel list it looks like he has a fix in and will rebuild the official image(s).

Thanks!
