### ISSUE TITLE
Why Azure Not provide CentOS Official version

### ISSUE THREAD

**Issue by cpsc** [openlogic/AzureBuildCentOS#44]
Hi 
I have a question
Why Azure Not provide CentOS Official version，but have Roguewave provide CentOS version。
he provide image part / only 30g ,

```part / --asprimary --fstype="xfs" --size=30219```

**Comment by szarkos** [comment]
Microsoft Azure does not publish the images, that various partners and distributions do. We are working with the CentOS community to help them offer their own image(s).  They have a KS for CentOS here, which I've contributed to: https://github.com/CentOS/sig-cloud-instance-build/tree/master/cloudimg

Most of the Linux images in Azure have a standard size 30GB OS disk.  If you need additional space then it is feasible to extend the VHD, or attach a data disk.

Thanks,
Steve
