### ISSUE TITLE
Module list in centos76-hpc-sriov.ks

### ISSUE THREAD

**Issue by vermagit** [openlogic/AzureBuildCentOS#68]
Should we remove the version from the module listing?
Ex:
cat << EOF >> /usr/share/Modules/modulefiles/mpi/openmpi**-4.0.1**

Changing versions (if using 'latest' image) makes automation from scripts (which depend on a module load for the right paths) a challenge. Keeping the versions in the listing might make sense once we offer different versions together.

**Comment by jithinjosepkl** [comment]
Advantage of having the version prefix is to easily identify the version. Automation scripts can easily identify the module using a file search. That being said, I am ok with changing the module name format without the version prefix.

**Comment by vermagit** [comment]
I agree it is easy to identify the version. However having the minor versions included might be more detail than most might need immediate access to. This apart from requiring automated scripts to keep up more frequently with minor version updates.
Doing a search and grep to identify which module to include sort of takes away the convenience of simply "module load".
At the very least, how about dropping minor versions from all modules?
