### ISSUE TITLE
Question about image building

### ISSUE THREAD

**Issue by Klaas-** [openlogic/AzureBuildCentOS#71]
Hi,
I have a question about how you automate the image building process for Azure. Do you use weldr(lorax-composer) or something like that? I am trying to figure out the proper way to built custom azure images in an automated fashion.

Greetings
Klaas

**Comment by szarkos** [comment]
I think Roguewave has written some scripts to automate building a VM in Hyper-V.  On the CentOS and RHEL image side I believe they just use virt-install and some shell scripts, i.e. I use something like this to build test images:

qemu-img create -f qcow2 ./azure-centos7.qcow2 8G

virt-install \
    --name centos7 \
    --ram 2048 \
    --disk path=./azure-centos7.qcow2,size=8 \
    --vcpus 1 \
    --os-type linux \
    --network bridge=virbr0 \
    --graphics none \
    --console pty,target_type=serial \
    --location 'http://mirror.centos.org/centos/7/os/x86_64' \
    --extra-args 'console=ttyS0,115200n8 serial ks=https://raw.githubusercontent.com/CentOS/sig-cloud-instance-build/master/cloudimg/CentOS-7-x86_64-Azure.ks'

So, yeah, nothing really elaborate :)

**Comment by Klaas-** [comment]
Is that how you create production images for azure? Are they built on a linux host with libvirt? I thought there would be an automated pipeline with jenkins/azure devops/whatever and I was wondering if that is on github somewhere :)

**Comment by szarkos** [comment]
I haven't worked on any automation myself.  Roguewave builds on Hyper-V for the Azure images, and the automation is not on Github.

I believe the official CentOS images (https://github.com/CentOS/sig-cloud-instance-build/tree/master/cloudimg) do use virt-install, but I don't know if that automation is public either :/
