### ISSUE TITLE
Support for MLX5

### ISSUE THREAD

**Issue by lmiroslaw** [openlogic/AzureBuildCentOS#74]
Mellanox HCA driver supports both mlx4 and mlx5. However after deploying your image I see only mlx4. Therefore, I cannot run OSU benchmarks as documented (see Airlift MPI talk). 

How to enable mlx5?

see https://docs.mellanox.com/display/MLNXOFEDv461000/Release+Notes

**Comment by lmiroslaw** [comment]
I checked and ConnectX-4 is not available. 

See [cycleadmin@ip-0A000005 ~]$ lspci | grep Mellanox
afb6:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]

**Comment by shirgall** [comment]
Connect-X 4 only shows on specific hardware SKUs. Are you choosing a VM size that explicitly has CX4 like Lv2, HB, or HC sizes?

**Comment by szarkos** [comment]
Closing this for now as we've not seen any updates in a while. Feel free to re-open if needed. Thanks.
