### ISSUE TITLE
Add python3 package to CentOS 8 image configuration

### ISSUE THREAD

**Issue by szarkos** [openlogic/AzureBuildCentOS#90]
The CentOS 8 image includes a number of Python core libraries needed for things like the Azure agent (WALinuxAgent package), but some VM extensions and other customer scripts will need /usr/bin/python3 available explicitly.  We suggest adding the python3 package directly in the kickstart.

**Comment by N3WWN** [comment]
@szarkos , since the refreshed CentOS 8.0 image tested good and included python3, I think we can close this issue.
