### ISSUE TITLE
CentOS 8.1 (+HPC) images

### ISSUE THREAD

**Issue by tbugfinder** [openlogic/AzureBuildCentOS#91]
Hi, 
as CentOS8.1 was released, I'm looking for a given image within Azure.
Would it be possible to add CentOS8.1 / CentOS8.1 HPC images also?

**Comment by N3WWN** [comment]
Hi!

CentOS 8.1 is on our schedule to be built, tested and published in the Azure Marketplace ASAP.  

The CentOS 8.x HPC images require additional work to get the HPC components updated for the new major release, but this is also on our short-term schedule.

Thanks!

**Comment by tbugfinder** [comment]
Hi @N3WWN ,

thank you for your reply.
Do you have any kind of estimated release date?


Stay healthy!

Best!

**Comment by N3WWN** [comment]
Hi @tbugfinder !

CentOS 8.1 was published on Feb 27th, so you should be able to find it in the Azure Marketplace: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/openlogic.centos?tab=PlansAndPrice

I'm afraid I don't have an updated estimate for the CentOS 8.x HPC image.

Please feel free to follow up again if you don't see it shortly.

Thanks and I hope that you stay healthy, too!

**Comment by N3WWN** [comment]
@tbugfinder I'm pleased to announce that the CentOS 8.1 HPC image was released about an hour ago.  

Please try it out and let me know if you have any issues.

Thanks!

**Comment by tbugfinder** [comment]
That's great news, will do asap. Thank you.

**Comment by N3WWN** [comment]
Having not heard about any issues, I'm going to assume everything is working well and am closing this issue. 😁
