### ISSUE TITLE
7.7 vs 7.8 vs 8.1: /dev/sdb1 mount point

### ISSUE THREAD

**Issue by yellowhat** [openlogic/AzureBuildCentOS#98]
Hi,
I noticed that images:
- `OpenLogic:CentOS:7_7-gen2:latest`
- `OpenLogic:CentOS:7_8-gen2:latest`
- `OpenLogic:CentOS:8_1-gen2:latest`
treat `/dev/sdb1` in a different way:

```
$ cat /etc/redhat-release; lsblk /dev/sdb; cat /etc/fstab; (grep "Disk" /etc/waagent.conf)
CentOS Linux release 7.7.1908 (Core)
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sdb      8:16   0   4G  0 disk
`-sdb1   8:17   0   4G  0 part /mnt/resource

#
# /etc/fstab
# Created by anaconda on Wed Apr 29 16:12:57 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=148be922-e3ec-43b5-8705-69786b522b05 /                       xfs     defaults        0 0
UUID=2a7bb59d-6a71-4841-a3c6-cba23413a5d2 /boot                   xfs     defaults        0 0
UUID=788D-DC65          /boot/efi               vfat    defaults,uid=0,gid=0,umask=0077,shortname=winnt 0 0
ResourceDisk.Format=y
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=n
ResourceDisk.SwapSizeMB=0
ResourceDisk.MountOptions=None
```

```
$ cat /etc/redhat-release; lsblk /dev/sdb; cat /etc/fstab; (grep "Disk" /etc/waagent.conf)
CentOS Linux release 7.8.2003 (Core)
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sdb      8:16   0   4G  0 disk
`-sdb1   8:17   0   4G  0 part /mnt

#
# /etc/fstab
# Created by anaconda on Tue May 19 12:26:23 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=c8eabcf3-212c-4d48-85fe-1abf6a19b17f /                       xfs     defaults        0 0
UUID=6d03eae4-603f-4b90-a127-7cf99f76e26c /boot                   xfs     defaults        0 0
UUID=06E6-139C          /boot/efi               vfat    defaults,uid=0,gid=0,umask=0077,shortname=winnt 0 0
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig       0       2
ResourceDisk.Format=n
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=n
ResourceDisk.SwapSizeMB=0
ResourceDisk.MountOptions=None
```

```
cat /etc/redhat-release; lsblk /dev/sdb; cat /etc/fstab; (grep "Disk" /etc/waagent.conf)
CentOS Linux release 8.1.1911 (Core)
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sdb      8:16   0   4G  0 disk
└─sdb1   8:17   0   4G  0 part

#
# /etc/fstab
# Created by anaconda on Wed Apr 29 16:27:02 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
#
# After editing this file, run 'systemctl daemon-reload' to update systemd
# units generated from this file.
#
UUID=1a602e87-4032-4880-9438-fb6404b4fe5c /                       xfs     defaults        0 0
UUID=5adc30e5-875e-4bfa-a0ab-9e301fddc65d /boot                   xfs     defaults        0 0
UUID=AD37-42AC          /boot/efi               vfat    defaults,uid=0,gid=0,umask=077,shortname=winnt 0 2
ResourceDisk.Format=y
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=n
ResourceDisk.SwapSizeMB=0
ResourceDisk.MountOptions=None
```

Is there a particular reason?

Thanks

**Comment by Klaas-** [comment]
I can tell you about the 8.1 issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1801317

you can cleanly apply https://git.centos.org/rpms/WALinuxAgent/raw/c7-extras/f/SOURCES/wla-Add-support-for-Gen2-VM-resource-disks-1654.patch to get it working with your favorite tools (ansible for example)

**Comment by N3WWN** [comment]
The difference between 7.7 and 7.8 is that 7.7 currently has the ephemeral disk provisioned by waagent whereas 7.8 provisions the ephemeral disk with cloud-init.  

With CentOS 8, we realigned our kickstart with the RHEL 8 kickstart, so the behavior should be the same with CentOS 8 and RHEL 8 within Azure. 

The 7.7 and 8.1 images will soon be updated with cloud-init provisioning which should make 7.7 and 7.8 identical again as well as catching up the 8.1 images with the RHEL behavior.

**Comment by Klaas-** [comment]
@N3WWN so is the ephemeral disk supposed to be provisioned with cloud init or with walinuxagent? And is it supposed to be at /mnt or /mnt/resource? :)

**Comment by N3WWN** [comment]
At present, CentOS 7.7 and older are all provisioned with waagent, as are CentOS 8.0 and CentOS 8.1.  

Starting with CentOS 7.8 and CentOS 8.2 (when it is released), cloud-init will handle the provisioning.  

We will release updates to the CentOS 7.7 images to switch over to cloud-init also.

In CentOS 7, the /mnt mountpoint is set by cloud-init and is correct for cloud-init provisioned images and /mnt/resource is set by waagent and is correct for waagent provisioned images.

I will inquire with my Azure infrastructure contacts to verify that this is correct behavior, though.

**Comment by N3WWN** [comment]
Sorry for the long delay following up on this ticket, but on June 23, 2020, we got approval to mount the ephemeral disk at /mnt/resource for all of our CentOS images.  

The images published later that week (and the following week) included that consistent mount point.
